export const dummyHotelsObj = [
  {
    hotel_id: 11137061,
    accessibilityLabel:
      "1BR Apartment in Diar El-Rabwa.\n‎2.4 km from center‬.\n 55 m² : 3 beds • 1 bedroom • 1 living room • 1 bathroom.\nOriginal price 684 USD. Current price 547 USD..\n+82 USD taxes and charges.",
    property: {
      countryCode: "eg",
      rankingPosition: 0,
      accuratePropertyClass: 0,
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      priceBreakdown: {
        grossPrice: {
          currency: "USD",
          value: 547.2,
        },
        taxExceptions: [],
        benefitBadges: [],
        excludedPrice: {
          currency: "USD",
          value: 82.08,
        },
        strikethroughPrice: {
          value: 684,
          currency: "USD",
        },
      },
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/509178667.jpg?k=1470f80584864343e612464fb9a3a78546ae5ca813e1bf40194704a3ed9be511&o=",
      ],
      wishlistName: "Sharm El Sheikh",
      qualityClass: 0,
      longitude: 34.309015664424,
      mainPhotoId: 509178667,
      ufi: -302053,
      currency: "USD",
      blockIds: ["1113706101_384292405_3_0_0"],
      checkinDate: "2023-11-29",
      propertyClass: 0,
      reviewCount: 0,
      position: 0,
      checkin: {
        untilTime: "00:00",
        fromTime: "15:00",
      },
      checkout: {
        untilTime: "00:00",
        fromTime: "00:00",
      },
      latitude: 27.903409800817,
      name: "1BR Apartment in Diar El-Rabwa",
      reviewScoreWord: "",
      reviewScore: 0,
      id: 11137061,
      checkoutDate: "2023-12-23",
    },
  },
  {
    hotel_id: 8985089,
    accessibilityLabel:
      "Morning Star Guesthouse.\n9.4 Wonderful 106 reviews.\n‎4.3 km from center‬\n‎2.9 km from beach‬\n‎Travel Sustainable‬.\n Room with shared bathroom : 2 beds.\nOriginal price 850 USD. Current price 680 USD..\n+128 USD taxes and charges.",
    property: {
      reviewCount: 106,
      propertyClass: 0,
      isPreferred: true,
      checkinDate: "2023-11-29",
      blockIds: ["898508904_373756334_2_0_0"],
      ufi: -302053,
      mainPhotoId: 423432247,
      currency: "USD",
      longitude: 34.2975836927502,
      qualityClass: 0,
      wishlistName: "Sharm El Sheikh",
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/423432247.jpg?k=9a4e0cf6cc7e0e9664c9643f41156cd0d82c221aec883d2493903beac68f057e&o=",
      ],
      priceBreakdown: {
        excludedPrice: {
          currency: "USD",
          value: 128,
        },
        strikethroughPrice: {
          value: 850,
          currency: "USD",
        },
        grossPrice: {
          currency: "USD",
          value: 680,
        },
        benefitBadges: [
          {
            explanation: "Mobile-only price",
            text: "Mobile-only price",
            variant: "constructive",
            identifier: "Mobile Rate",
          },
        ],
        taxExceptions: [],
      },
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      accuratePropertyClass: 0,
      countryCode: "eg",
      rankingPosition: 1,
      checkoutDate: "2023-12-23",
      reviewScore: 9.4,
      id: 8985089,
      reviewScoreWord: "Wonderful",
      name: "Morning Star Guesthouse",
      latitude: 27.8888899725518,
      checkout: {
        fromTime: "08:00",
        untilTime: "11:00",
      },
      checkin: {
        untilTime: "00:00",
        fromTime: "00:00",
      },
      position: 1,
    },
  },
  {
    hotel_id: 7664918,
    accessibilityLabel:
      "JUMERA HOUSE CRISS RESORT NAAMA Bay.\n3 out of 5 for property rating.\n6.5 Pleasant 19 reviews.\n‎In city center‬\n‎1.2 km from beach‬.\n Entire apartment : 3 beds • 1 bedroom • 1 living room • 1 bathroom.\n126 USD.\n+403 USD taxes and charges.",
    property: {
      wishlistName: "Sharm El Sheikh",
      priceBreakdown: {
        excludedPrice: {
          currency: "USD",
          value: 402.9,
        },
        benefitBadges: [],
        taxExceptions: [],
        grossPrice: {
          value: 126,
          currency: "USD",
        },
      },
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/471084063.jpg?k=9cdaeef05f30c8eed04628ccc16fb77000c5febcdd9e7368e25bfc3397576022&o=",
      ],
      accuratePropertyClass: 0,
      countryCode: "eg",
      rankingPosition: 2,
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      checkinDate: "2023-11-29",
      reviewCount: 19,
      propertyClass: 0,
      longitude: 34.3147834279487,
      qualityClass: 3,
      blockIds: ["766491804_381261619_2_0_0"],
      ufi: -302053,
      mainPhotoId: 471084063,
      currency: "USD",
      name: "JUMERA HOUSE CRISS RESORT NAAMA Bay",
      latitude: 27.9121362810965,
      checkout: {
        fromTime: "10:00",
        untilTime: "11:00",
      },
      position: 2,
      checkin: {
        untilTime: "00:00",
        fromTime: "11:00",
      },
      reviewScoreWord: "Pleasant",
      checkoutDate: "2023-12-23",
      reviewScore: 6.5,
      id: 7664918,
    },
  },
  {
    hotel_id: 11095376,
    accessibilityLabel:
      "Normally Apartment.\n‎El Hadaba‬ • ‎4.2 km from center‬\n‎2.4 km from beach‬.\n 75 m² : 3 beds • 1 bedroom • 1 living room • 1 bathroom.\n359 USD.\n+54 USD taxes and charges.",
    property: {
      wishlistName: "Sharm El Sheikh",
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/507185081.jpg?k=4a6d788114dbcbf6f351af20b56b5f2412439c0ea6c3a26a9e96030fe8f67d53&o=",
      ],
      priceBreakdown: {
        excludedPrice: {
          currency: "USD",
          value: 53.856,
        },
        grossPrice: {
          currency: "USD",
          value: 359.04,
        },
        benefitBadges: [],
        taxExceptions: [],
      },
      accuratePropertyClass: 0,
      rankingPosition: 3,
      countryCode: "eg",
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      checkinDate: "2023-11-29",
      reviewCount: 0,
      propertyClass: 0,
      longitude: 34.3042552,
      qualityClass: 0,
      blockIds: ["1109537601_383708019_1_0_0"],
      currency: "USD",
      ufi: -302053,
      mainPhotoId: 507185081,
      name: "Normally Apartment",
      latitude: 27.8852202,
      checkout: {
        fromTime: "08:00",
        untilTime: "11:00",
      },
      position: 3,
      checkin: {
        untilTime: "18:00",
        fromTime: "15:00",
      },
      reviewScoreWord: "",
      reviewScore: 0,
      checkoutDate: "2023-12-23",
      id: 11095376,
    },
  },
  {
    hotel_id: 10986713,
    accessibilityLabel:
      "Golden Rent Porto Sharm.\n‎16 km from center‬\n‎2.9 km from beach‬\n‎Travel Sustainable‬.\n Entire chalet : 2 beds • 1 bedroom • 1 living room • 2 bathrooms.\nOriginal price 373 USD. Current price 271 USD..\n+41 USD taxes and charges.\nNo prepayment needed.",
    property: {
      rankingPosition: 4,
      countryCode: "eg",
      accuratePropertyClass: 0,
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      priceBreakdown: {
        strikethroughPrice: {
          currency: "USD",
          value: 372.8,
        },
        excludedPrice: {
          value: 40.6515,
          currency: "USD",
        },
        benefitBadges: [
          {
            text: "Mobile-only price",
            explanation: "Mobile-only price",
            variant: "constructive",
            identifier: "Mobile Rate",
          },
        ],
        taxExceptions: [],
        grossPrice: {
          currency: "USD",
          value: 271.01,
        },
      },
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/502333446.jpg?k=e8063dc5fe4dba7848dce883c581e92e1760bde6938646db125ab4fc2dfee0e2&o=",
      ],
      wishlistName: "Sharm El Sheikh",
      qualityClass: 0,
      longitude: 34.406632781548,
      mainPhotoId: 502333446,
      ufi: -302053,
      currency: "USD",
      blockIds: ["1098671302_383686507_1_0_0"],
      checkinDate: "2023-11-29",
      reviewCount: 0,
      propertyClass: 0,
      position: 4,
      checkin: {
        fromTime: "10:00",
        untilTime: "18:00",
      },
      checkout: {
        untilTime: "12:00",
        fromTime: "09:00",
      },
      latitude: 28.037196908351,
      name: "Golden Rent Porto Sharm",
      reviewScoreWord: "",
      reviewScore: 0,
      checkoutDate: "2023-12-23",
      id: 10986713,
    },
  },
  {
    hotel_id: 343566,
    accessibilityLabel:
      "Sharm Inn Amarein - Boutique Hotel.\n4 out of 5 stars.\n8.4 Very Good 1816 reviews.\n‎El Hadaba‬ • ‎5 km from center‬\n‎1.6 km from beach‬\n‎Travel Sustainable‬.\n Hotel room : 3 beds.\nOriginal price 1229 USD. Current price 615 USD..\n+177 USD taxes and charges.",
    property: {
      isPreferred: true,
      checkinDate: "2023-11-29",
      propertyClass: 4,
      reviewCount: 1816,
      longitude: 34.3062345549151,
      qualityClass: 0,
      blockIds: ["34356601_383080729_1_41_0"],
      ufi: -302053,
      mainPhotoId: 11648619,
      currency: "USD",
      wishlistName: "Sharm El Sheikh",
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/11648619.jpg?k=74dd8754d8df1fa98d97bfde3cf0c6ff17f3cf3e1d6f09e3227c9d7142d2684e&o=",
      ],
      priceBreakdown: {
        grossPrice: {
          value: 614.54,
          currency: "USD",
        },
        benefitBadges: [
          {
            identifier: "Black Friday",
            text: "Black Friday Deal",
            explanation: "Black Friday Deal",
          },
        ],
        taxExceptions: [],
        excludedPrice: {
          value: 176.98752,
          currency: "USD",
        },
        strikethroughPrice: {
          currency: "USD",
          value: 1229.07,
        },
      },
      accuratePropertyClass: 4,
      rankingPosition: 5,
      countryCode: "eg",
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      reviewScoreWord: "Very Good",
      reviewScore: 8.4,
      id: 343566,
      checkoutDate: "2023-12-23",
      name: "Sharm Inn Amarein - Boutique Hotel",
      latitude: 27.8740330453823,
      checkout: {
        fromTime: "00:00",
        untilTime: "12:00",
      },
      position: 5,
      checkin: {
        fromTime: "14:00",
        untilTime: "00:00",
      },
      isPreferredPlus: true,
    },
  },
  {
    hotel_id: 9441616,
    accessibilityLabel:
      "Regency Lodge.\n3 out of 5 for property rating.\n7.6 Good 155 reviews.\n‎El Hadaba‬ • ‎6 km from center‬\n‎650 m from beach‬\n‎Travel Sustainable‬.\n Private room : 1 bed.\nOriginal price 434 USD. Current price 356 USD..\n+53 USD taxes and charges.\nNo prepayment needed.",
    property: {
      qualityClass: 3,
      longitude: 34.304448784758,
      currency: "USD",
      mainPhotoId: 417245244,
      ufi: -302053,
      blockIds: ["944161606_381405079_1_25_0"],
      checkinDate: "2023-11-29",
      isPreferred: true,
      reviewCount: 155,
      propertyClass: 0,
      rankingPosition: 6,
      countryCode: "eg",
      accuratePropertyClass: 0,
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/417245244.jpg?k=594cdc1b61749f600582ce3087388d137082da2889004daed04028ce1811a5bc&o=",
      ],
      priceBreakdown: {
        taxExceptions: [],
        benefitBadges: [
          {
            identifier: "Late Escape Campaign",
            variant: "constructive",
            text: "Late Escape Deal",
            explanation: "Late Escape Deal",
          },
        ],
        grossPrice: {
          currency: "USD",
          value: 355.88,
        },
        strikethroughPrice: {
          value: 434,
          currency: "USD",
        },
        excludedPrice: {
          currency: "USD",
          value: 53.382,
        },
      },
      wishlistName: "Sharm El Sheikh",
      reviewScoreWord: "Good",
      checkoutDate: "2023-12-23",
      reviewScore: 7.6,
      id: 9441616,
      position: 6,
      checkin: {
        untilTime: "22:00",
        fromTime: "11:00",
      },
      latitude: 27.862114551752,
      checkout: {
        fromTime: "11:00",
        untilTime: "12:00",
      },
      name: "Regency Lodge",
    },
  },
  {
    hotel_id: 1664918,
    accessibilityLabel:
      "Steigenberger Alcazar.\n5 out of 5 stars.\n9.4 Wonderful 2860 reviews.\n‎Nabq Bay‬ • ‎19 km from center‬\n‎Beachfront‬\n‎Travel Sustainable‬.\nBeds: 1 double or 2 twins.\nOriginal price 3308 USD. Current price 2812 USD..\n+778 USD taxes and charges.\nNo prepayment needed.",
    property: {
      checkout: {
        fromTime: "00:00",
        untilTime: "12:00",
      },
      latitude: 28.0614454863252,
      name: "Steigenberger Alcazar",
      checkin: {
        untilTime: "00:00",
        fromTime: "14:00",
      },
      position: 7,
      reviewScore: 9.4,
      id: 1664918,
      checkoutDate: "2023-12-23",
      reviewScoreWord: "Wonderful",
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/498857247.jpg?k=e6986eef0c9ff04a5446e1df1b26508d273572501a03d32aa486e386b2f881a1&o=",
      ],
      priceBreakdown: {
        excludedPrice: {
          currency: "USD",
          value: 778.400352,
        },
        strikethroughPrice: {
          value: 3308.4,
          currency: "USD",
        },
        grossPrice: {
          value: 2812.14,
          currency: "USD",
        },
        taxExceptions: [],
        benefitBadges: [],
      },
      wishlistName: "Sharm El Sheikh",
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      countryCode: "eg",
      rankingPosition: 7,
      accuratePropertyClass: 5,
      propertyClass: 5,
      reviewCount: 2860,
      checkinDate: "2023-11-29",
      isPreferred: true,
      ufi: -302053,
      mainPhotoId: 498857247,
      currency: "USD",
      blockIds: ["166491801_366932368_1_41_0"],
      qualityClass: 0,
      longitude: 34.4333325878968,
    },
  },
  {
    hotel_id: 304165,
    accessibilityLabel:
      "Viva Sharm.\n3 out of 5 stars.\n7.1 Good 683 reviews.\n‎El Hadaba‬ • ‎5 km from center‬\n‎900 m from beach‬.\n Hotel room : 1 bed.\nOriginal price 408 USD. Current price 330 USD..\n+95 USD taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    property: {
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      countryCode: "eg",
      rankingPosition: 8,
      accuratePropertyClass: 3,
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/116311664.jpg?k=49e28292da633731ffe7b4c5ea49480fd446271f0a0d0c4a7ee70962d105f3ef&o=",
      ],
      priceBreakdown: {
        excludedPrice: {
          currency: "USD",
          value: 95.17824,
        },
        strikethroughPrice: {
          value: 408,
          currency: "USD",
        },
        grossPrice: {
          currency: "USD",
          value: 330.48,
        },
        benefitBadges: [
          {
            variant: "constructive",
            text: "Mobile-only price",
            explanation: "Mobile-only price",
            identifier: "Mobile Rate",
          },
        ],
        taxExceptions: [],
      },
      wishlistName: "Sharm El Sheikh",
      currency: "USD",
      ufi: -302053,
      mainPhotoId: 116311664,
      blockIds: ["30416502_338171406_0_42_0"],
      qualityClass: 0,
      longitude: 34.3137413263321,
      reviewCount: 683,
      propertyClass: 3,
      checkinDate: "2023-11-29",
      isPreferred: true,
      checkin: {
        fromTime: "14:00",
        untilTime: "00:00",
      },
      position: 8,
      latitude: 27.8706730527121,
      checkout: {
        untilTime: "12:00",
        fromTime: "00:00",
      },
      name: "Viva Sharm",
      reviewScore: 7.1,
      id: 304165,
      checkoutDate: "2023-12-23",
      reviewScoreWord: "Good",
    },
  },
  {
    hotel_id: 237466,
    accessibilityLabel:
      "Stella Di Mare Beach Hotel & Spa.\n5 out of 5 stars.\n8.8 Excellent 3495 reviews.\n‎In city center‬\n‎Beachfront‬\n‎Travel Sustainable‬.\n Hotel room : 2 beds.\nOriginal price 1933 USD. Current price 1488 USD..\n+429 USD taxes and charges.",
    property: {
      checkoutDate: "2023-12-23",
      reviewScore: 8.8,
      id: 237466,
      reviewScoreWord: "Excellent",
      name: "Stella Di Mare Beach Hotel & Spa",
      latitude: 27.9048492387473,
      checkout: {
        untilTime: "13:00",
        fromTime: "02:00",
      },
      checkin: {
        untilTime: "23:30",
        fromTime: "14:00",
      },
      position: 9,
      reviewCount: 3495,
      propertyClass: 5,
      isPreferred: true,
      checkinDate: "2023-11-29",
      blockIds: ["23746606_92667796_1_41_0"],
      mainPhotoId: 81552240,
      ufi: -302053,
      currency: "USD",
      longitude: 34.3272677063942,
      qualityClass: 0,
      wishlistName: "Sharm El Sheikh",
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/81552240.jpg?k=dfc6753624352520a18eb56ff22579c6c6920b6dbed1cc504ddf101ff55b074c&o=",
      ],
      priceBreakdown: {
        grossPrice: {
          currency: "USD",
          value: 1488.12,
        },
        taxExceptions: [],
        benefitBadges: [],
        excludedPrice: {
          value: 428.57856,
          currency: "USD",
        },
        strikethroughPrice: {
          value: 1932.62,
          currency: "USD",
        },
      },
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      accuratePropertyClass: 5,
      countryCode: "eg",
      rankingPosition: 9,
    },
  },
  {
    hotel_id: 172957,
    accessibilityLabel:
      "Jaz Mirabel Resort.\n5 out of 5 stars.\n8.5 Very Good 1488 reviews.\n‎Nabq Bay‬ • ‎19 km from center‬\n‎Beachfront‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\n1673 USD.\n+463 USD taxes and charges.",
    property: {
      checkin: {
        untilTime: "23:30",
        fromTime: "14:00",
      },
      position: 10,
      name: "Jaz Mirabel Resort",
      checkout: {
        untilTime: "12:00",
        fromTime: "07:00",
      },
      latitude: 28.0573627772837,
      reviewScore: 8.5,
      checkoutDate: "2023-12-23",
      id: 172957,
      reviewScoreWord: "Very Good",
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      accuratePropertyClass: 5,
      countryCode: "eg",
      rankingPosition: 10,
      wishlistName: "Sharm El Sheikh",
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/140455844.jpg?k=e1df33a014ecd45318f71a884fb03649b5bdb21d2596f328d5dc7db1dc091685&o=",
      ],
      priceBreakdown: {
        grossPrice: {
          currency: "USD",
          value: 1673.04,
        },
        taxExceptions: [],
        benefitBadges: [],
        excludedPrice: {
          value: 463.097472,
          currency: "USD",
        },
      },
      blockIds: ["17295724_375502369_1_85_0"],
      mainPhotoId: 140455844,
      ufi: -302053,
      currency: "USD",
      longitude: 34.4378471374512,
      qualityClass: 0,
      reviewCount: 1488,
      propertyClass: 5,
      isPreferred: true,
      checkinDate: "2023-11-29",
    },
  },
  {
    hotel_id: 171411,
    accessibilityLabel:
      "Dive Inn Resort.\n3 out of 5 stars.\n7.4 Good 764 reviews.\n‎El Hadaba‬ • ‎6 km from center‬\n‎1.3 km from beach‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\nOriginal price 665 USD. Current price 466 USD..\n+134 USD taxes and charges.",
    property: {
      name: "Dive Inn Resort",
      latitude: 27.8651719929798,
      checkout: {
        untilTime: "12:00",
        fromTime: "00:00",
      },
      checkin: {
        fromTime: "14:00",
        untilTime: "00:00",
      },
      position: 11,
      id: 171411,
      reviewScore: 7.4,
      checkoutDate: "2023-12-23",
      reviewScoreWord: "Good",
      wishlistName: "Sharm El Sheikh",
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/124209271.jpg?k=f848ec75ab2f9bd1dec41d98b42e81d9afac1a5bafa2c20e991b75de95f55c60&o=",
      ],
      priceBreakdown: {
        taxExceptions: [],
        benefitBadges: [
          {
            text: "Black Friday Deal",
            explanation: "Black Friday Deal",
            identifier: "Black Friday",
          },
        ],
        grossPrice: {
          currency: "USD",
          value: 465.7,
        },
        strikethroughPrice: {
          value: 665.28,
          currency: "USD",
        },
        excludedPrice: {
          value: 134.1216,
          currency: "USD",
        },
      },
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      accuratePropertyClass: 3,
      rankingPosition: 11,
      countryCode: "eg",
      reviewCount: 764,
      propertyClass: 3,
      isPreferred: true,
      checkinDate: "2023-11-29",
      blockIds: ["17141111_91909886_1_42_0"],
      currency: "USD",
      ufi: -302053,
      mainPhotoId: 124209271,
      longitude: 34.3110859394073,
      qualityClass: 0,
    },
  },
  {
    hotel_id: 16049,
    accessibilityLabel:
      "Jaz Belvedere Resort.\n5 out of 5 stars.\n8.5 Very Good 888 reviews.\n‎12 km from center‬\n‎Beachfront‬\n‎Travel Sustainable‬.\n2 beds.\nOriginal price 1767 USD. Current price 1590 USD..\n+440 USD taxes and charges.\nNo prepayment needed.",
    property: {
      position: 12,
      checkin: {
        untilTime: "00:00",
        fromTime: "14:00",
      },
      name: "Jaz Belvedere Resort",
      latitude: 27.9813935216328,
      checkout: {
        fromTime: "00:00",
        untilTime: "12:00",
      },
      reviewScoreWord: "Very Good",
      reviewScore: 8.5,
      checkoutDate: "2023-12-23",
      id: 16049,
      accuratePropertyClass: 5,
      rankingPosition: 12,
      countryCode: "eg",
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      wishlistName: "Sharm El Sheikh",
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/132418236.jpg?k=233287819f065f79fe0c18a58cc11552b899d34ae6bd873341ee856a0683817c&o=",
      ],
      priceBreakdown: {
        grossPrice: {
          value: 1590.41,
          currency: "USD",
        },
        taxExceptions: [],
        benefitBadges: [
          {
            identifier: "Mobile Rate",
            variant: "constructive",
            text: "Mobile-only price",
            explanation: "Mobile-only price",
          },
        ],
        excludedPrice: {
          currency: "USD",
          value: 440.225488,
        },
        strikethroughPrice: {
          currency: "USD",
          value: 1767.12,
        },
      },
      longitude: 34.4219952821732,
      qualityClass: 0,
      blockIds: ["1604915_309897973_1_85_0"],
      currency: "USD",
      mainPhotoId: 132418236,
      ufi: -302053,
      isPreferred: true,
      checkinDate: "2023-11-29",
      propertyClass: 5,
      reviewCount: 888,
    },
  },
  {
    hotel_id: 416026,
    accessibilityLabel:
      "Naama Inn Hotel.\n3 out of 5 stars.\n7.4 Good 1252 reviews.\n‎In city center‬\n‎400 m from beach‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\nOriginal price 552 USD. Current price 497 USD..\n+143 USD taxes and charges.\nNo prepayment needed.",
    property: {
      reviewScoreWord: "Good",
      id: 416026,
      reviewScore: 7.4,
      checkoutDate: "2023-12-23",
      position: 13,
      checkin: {
        untilTime: "00:00",
        fromTime: "14:00",
      },
      latitude: 27.9097035818689,
      checkout: {
        untilTime: "12:00",
        fromTime: "00:00",
      },
      name: "Naama Inn Hotel",
      qualityClass: 0,
      longitude: 34.3226543068886,
      currency: "USD",
      mainPhotoId: 61263802,
      ufi: -302053,
      blockIds: ["41602601_156924407_0_42_0"],
      checkinDate: "2023-11-29",
      reviewCount: 1252,
      propertyClass: 3,
      countryCode: "eg",
      rankingPosition: 13,
      accuratePropertyClass: 3,
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      priceBreakdown: {
        excludedPrice: {
          value: 143.0784,
          currency: "USD",
        },
        strikethroughPrice: {
          currency: "USD",
          value: 552,
        },
        grossPrice: {
          currency: "USD",
          value: 496.8,
        },
        benefitBadges: [
          {
            explanation: "Mobile-only price",
            text: "Mobile-only price",
            variant: "constructive",
            identifier: "Mobile Rate",
          },
        ],
        taxExceptions: [],
      },
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/61263802.jpg?k=2da78a4b86eb278e9c0b9993d0d0670124ce3ffd7bec8e5d2a9d6b43ace8bb08&o=",
      ],
      wishlistName: "Sharm El Sheikh",
    },
  },
  {
    hotel_id: 46949,
    accessibilityLabel:
      "Jaz Sharm Dreams.\n5 out of 5 stars.\n8.3 Very Good 1538 reviews.\n‎In city center‬\n‎350 m from beach‬\n‎Travel Sustainable‬.\n1 bed.\nOriginal price 1099 USD. Current price 990 USD..\n+285 USD taxes and charges.",
    property: {
      qualityClass: 0,
      longitude: 34.3261921405792,
      ufi: -302053,
      mainPhotoId: 506537293,
      currency: "USD",
      blockIds: ["4694913_376703734_1_41_0"],
      checkinDate: "2023-11-29",
      isPreferred: true,
      propertyClass: 5,
      reviewCount: 1538,
      rankingPosition: 14,
      countryCode: "eg",
      accuratePropertyClass: 5,
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      priceBreakdown: {
        taxExceptions: [],
        benefitBadges: [
          {
            variant: "constructive",
            explanation: "Mobile-only price",
            text: "Mobile-only price",
            identifier: "Mobile Rate",
          },
        ],
        grossPrice: {
          value: 989.5,
          currency: "USD",
        },
        strikethroughPrice: {
          value: 1099.44,
          currency: "USD",
        },
        excludedPrice: {
          value: 284.976,
          currency: "USD",
        },
      },
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/506537293.jpg?k=a3ac2c17bdb858babd5032acc285785ebd7b99812d700d680c015d2af88e7ad5&o=",
      ],
      wishlistName: "Sharm El Sheikh",
      reviewScoreWord: "Very Good",
      reviewScore: 8.3,
      checkoutDate: "2023-12-23",
      id: 46949,
      position: 14,
      checkin: {
        fromTime: "15:00",
        untilTime: "00:00",
      },
      latitude: 27.9152948135656,
      checkout: {
        fromTime: "00:00",
        untilTime: "12:00",
      },
      name: "Jaz Sharm Dreams",
    },
  },
  {
    hotel_id: 304173,
    accessibilityLabel:
      "Sunrise Remal Resort.\n4 out of 5 stars.\n8.8 Excellent 785 reviews.\n‎10 km from center‬\n‎550 m from beach‬\n‎Travel Sustainable‬.\n2 beds.\n1389 USD.\n+400 USD taxes and charges.",
    property: {
      position: 15,
      checkin: {
        untilTime: "00:00",
        fromTime: "15:00",
      },
      name: "Sunrise Remal Resort",
      checkout: {
        fromTime: "00:00",
        untilTime: "12:00",
      },
      latitude: 27.9697390907528,
      reviewScoreWord: "Excellent",
      reviewScore: 8.8,
      id: 304173,
      checkoutDate: "2023-12-23",
      accuratePropertyClass: 4,
      countryCode: "eg",
      rankingPosition: 15,
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      wishlistName: "Sharm El Sheikh",
      priceBreakdown: {
        taxExceptions: [],
        benefitBadges: [],
        grossPrice: {
          value: 1389.1,
          currency: "USD",
        },
        excludedPrice: {
          currency: "USD",
          value: 400.0608,
        },
      },
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/318839001.jpg?k=c3897813206dfd718e33a5dea7f204f8b0a4086a4ab61a4b22c5246a5812eca9&o=",
      ],
      longitude: 34.4132941961288,
      qualityClass: 0,
      blockIds: ["30417305_356616971_1_85_0"],
      mainPhotoId: 318839001,
      ufi: -302053,
      currency: "USD",
      isPreferred: true,
      checkinDate: "2023-11-29",
      reviewCount: 785,
      propertyClass: 4,
    },
  },
  {
    hotel_id: 298504,
    accessibilityLabel:
      "Amwaj Oyoun Resort & Casino.\n4 out of 5 stars.\n7.8 Good 880 reviews.\n‎Nabq Bay‬ • ‎17 km from center‬\n‎Beachfront‬\n‎Travel Sustainable‬.\n Hotel room : Beds: 1 double or 2 twins.\nOriginal price 1440 USD. Current price 1008 USD..\n+290 USD taxes and charges.\nNo prepayment needed.",
    property: {
      longitude: 34.4356048107147,
      qualityClass: 0,
      blockIds: ["29850410_375407227_1_85_0"],
      currency: "USD",
      mainPhotoId: 247149826,
      ufi: -302053,
      checkinDate: "2023-11-29",
      reviewCount: 880,
      propertyClass: 4,
      accuratePropertyClass: 4,
      countryCode: "eg",
      rankingPosition: 16,
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      wishlistName: "Sharm El Sheikh",
      priceBreakdown: {
        excludedPrice: {
          value: 290.304,
          currency: "USD",
        },
        strikethroughPrice: {
          value: 1440,
          currency: "USD",
        },
        grossPrice: {
          currency: "USD",
          value: 1008,
        },
        benefitBadges: [
          {
            identifier: "Black Friday",
            text: "Black Friday Deal",
            explanation: "Black Friday Deal",
          },
        ],
        taxExceptions: [],
      },
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/247149826.jpg?k=981efddbf60a5cf8e8eb0bdb1161eb52add8c24335a132f6951d16d50c0a5388&o=",
      ],
      reviewScoreWord: "Good",
      reviewScore: 7.8,
      id: 298504,
      checkoutDate: "2023-12-23",
      position: 16,
      checkin: {
        untilTime: "00:00",
        fromTime: "14:00",
      },
      name: "Amwaj Oyoun Resort & Casino",
      checkout: {
        fromTime: "11:30",
        untilTime: "12:00",
      },
      latitude: 28.0350184551455,
    },
  },
  {
    hotel_id: 6299459,
    accessibilityLabel:
      "Delta Sharm Apartments with free Internet Wi-Fi.\n3 out of 5 for property rating.\n6.8 Pleasant 17 reviews.\n‎El Hadaba‬ • ‎4.2 km from center‬\n‎2.5 km from beach‬\n‎Travel Sustainable‬.\n Entire apartment – 12 m² : 4 beds • 1 bedroom • 1 living room • 1 bathroom.\n655 USD.\n+98 USD taxes and charges.",
    property: {
      position: 17,
      checkin: {
        untilTime: "00:00",
        fromTime: "12:00",
      },
      name: "Delta Sharm Apartments with free Internet Wi-Fi",
      latitude: 27.8851004,
      checkout: {
        untilTime: "12:00",
        fromTime: "00:00",
      },
      reviewScoreWord: "Pleasant",
      checkoutDate: "2023-12-23",
      reviewScore: 6.8,
      id: 6299459,
      accuratePropertyClass: 0,
      countryCode: "eg",
      rankingPosition: 17,
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      wishlistName: "Sharm El Sheikh",
      priceBreakdown: {
        grossPrice: {
          value: 654.59,
          currency: "USD",
        },
        taxExceptions: [],
        benefitBadges: [],
        excludedPrice: {
          currency: "USD",
          value: 98.1885,
        },
      },
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/254083217.jpg?k=d3db06e12935e8350ca65f4fa837cf6fb60e0c136ce63a07d52501a79e2f2c0d&o=",
      ],
      longitude: 34.3033744,
      qualityClass: 3,
      blockIds: ["629945901_335431676_1_0_0"],
      currency: "USD",
      ufi: -302053,
      mainPhotoId: 254083217,
      isPreferred: true,
      checkinDate: "2023-11-29",
      reviewCount: 17,
      propertyClass: 0,
    },
  },
  {
    hotel_id: 263895,
    accessibilityLabel:
      "Verginia Sharm Resort & Aqua Park.\n4 out of 5 stars.\n8.7 Excellent 900 reviews.\n‎El Hadaba‬ • ‎5 km from center‬\n‎1.1 km from beach‬\n‎Travel Sustainable‬.\n Hotel room : Beds: 1 double or 2 twins.\nOriginal price 960 USD. Current price 864 USD..\n+249 USD taxes and charges.",
    property: {
      reviewScore: 8.7,
      checkoutDate: "2023-12-23",
      id: 263895,
      reviewScoreWord: "Excellent",
      checkout: {
        untilTime: "12:00",
        fromTime: "00:00",
      },
      latitude: 27.8709860356447,
      name: "Verginia Sharm Resort & Aqua Park",
      isPreferredPlus: true,
      checkin: {
        fromTime: "14:00",
        untilTime: "00:00",
      },
      position: 18,
      reviewCount: 900,
      propertyClass: 4,
      checkinDate: "2023-11-29",
      isPreferred: true,
      ufi: -302053,
      mainPhotoId: 411594207,
      currency: "USD",
      blockIds: ["26389522_128758678_0_42_0"],
      qualityClass: 0,
      longitude: 34.3116009235382,
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/411594207.jpg?k=cac7bd93233ef7783d88dd78dfbbddedd884368c7fdadb0152868a4a865f0548&o=",
      ],
      priceBreakdown: {
        strikethroughPrice: {
          currency: "USD",
          value: 960,
        },
        excludedPrice: {
          value: 248.832,
          currency: "USD",
        },
        benefitBadges: [
          {
            identifier: "Mobile Rate",
            text: "Mobile-only price",
            explanation: "Mobile-only price",
            variant: "constructive",
          },
        ],
        taxExceptions: [],
        grossPrice: {
          value: 864,
          currency: "USD",
        },
      },
      wishlistName: "Sharm El Sheikh",
      isFirstPage: true,
      optOutFromGalleryChanges: 0,
      countryCode: "eg",
      rankingPosition: 18,
      accuratePropertyClass: 4,
    },
  },
  {
    hotel_id: 10934479,
    accessibilityLabel:
      "Sharks Bay Oasis Soft only & Aqua Park and Diving.\n4 out of 5 stars.\n8.3 Very Good 34 reviews.\n‎Sharks Bay‬ • ‎7 km from center‬\n‎Beachfront‬\n‎Travel Sustainable‬.\n Hotel room : 1 bed.\nOriginal price 836 USD. Current price 502 USD..\n+135 USD taxes and charges.\nFree cancellation.\nNo prepayment needed.",
    property: {
      photoUrls: [
        "https://cf.bstatic.com/xdata/images/hotel/square60/500301516.jpg?k=45541689be3963afa15b507ec6b962c46f3989c054bc7dabd2c84bec80d2faab&o=",
      ],
      priceBreakdown: {
        excludedPrice: {
          value: 135.432,
          currency: "USD",
        },
        strikethroughPrice: {
          value: 836,
          currency: "USD",
        },
        grossPrice: {
          currency: "USD",
          value: 501.6,
        },
        benefitBadges: [
          {
            variant: "constructive",
            explanation: "Mobile-only price",
            text: "Mobile-only price",
            identifier: "Mobile Rate",
          },
        ],
        taxExceptions: [],
      },
      wishlistName: "Sharm El Sheikh",
      optOutFromGalleryChanges: 0,
      isFirstPage: true,
      rankingPosition: 19,
      countryCode: "eg",
      accuratePropertyClass: 4,
      reviewCount: 34,
      propertyClass: 4,
      checkinDate: "2023-11-29",
      currency: "USD",
      ufi: -302053,
      mainPhotoId: 500301516,
      blockIds: ["1093447901_382607019_2_0_0"],
      qualityClass: 0,
      longitude: 34.386043935728,
      checkout: {
        fromTime: "12:00",
        untilTime: "12:00",
      },
      latitude: 27.952612081554,
      name: "Sharks Bay Oasis Soft only & Aqua Park and Diving",
      checkin: {
        fromTime: "14:00",
        untilTime: "00:00",
      },
      position: 19,
      checkoutDate: "2023-12-23",
      reviewScore: 8.3,
      id: 10934479,
      reviewScoreWord: "Very Good",
    },
  },
];
export const dummyHotel = {
  ufi: -302053,
  hotel_id: 8985089,
  hotel_name: "Morning Star Guesthouse",
  url: "https://www.booking.com/hotel/eg/morning-star-guest-house.html",
  hotel_name_trans: "",
  review_nr: 108,
  arrival_date: "2024-01-11",
  departure_date: "2024-03-01",
  price_transparency_mode: "none",
  accommodation_type_name: "Guesthouses",
  latitude: 27.8888899725518,
  longitude: 34.2975836927502,
  address: "Sharm El Sheikh - Dahab Road",
  address_trans: "",
  city: "Qesm Sharm Ash Sheikh",
  city_trans: "Sharm El Sheikh",
  city_in_trans: "in Sharm El Sheikh",
  city_name_en: "Sharm El Sheikh",
  district: "",
  countrycode: "eg",
  distance_to_cc: 4.27458256337596,
  default_language: "en-us",
  country_trans: "Egypt",
  currency_code: "USD",
  zip: "44026",
  timezone: "Africa/Cairo",
  rare_find_state: "NOT_RARE",
  soldout: 0,
  available_rooms: 1,
  max_rooms_in_reservation: 10,
  average_room_size_for_ufi_m2: "16.16",
  is_family_friendly: 0,
  is_closed: 0,
  is_crimea: 0,
  is_hotel_ctrip: 0,
  is_price_transparent: 0,
  is_genius_deal: 0,
  is_cash_accepted_check_enabled: 1,
  qualifies_for_no_cc_reservation: 0,
  hotel_include_breakfast: 0,
  cc1: "eg",
  family_facilities: ["Family rooms"],
  product_price_breakdown: {
    discounted_amount: {
      amount_unrounded: "US$245",
      amount_rounded: "US$245",
      currency: "USD",
      value: 245,
    },
    strikethrough_amount_per_night: {
      amount_unrounded: "US$24.50",
      value: 24.5,
      currency: "USD",
      amount_rounded: "US$25",
    },
    gross_amount_hotel_currency: {
      amount_unrounded: "US$980",
      currency: "USD",
      value: 980,
      amount_rounded: "US$980",
    },
    included_taxes_and_charges_amount: {
      amount_unrounded: "US$0",
      amount_rounded: "US$0",
      value: 0,
      currency: "USD",
    },
    charges_details: {
      mode: "extra_charges",
      amount: {
        value: 199,
        currency: "USD",
      },
      translated_copy: "+US$199 taxes and fees",
    },
    net_amount: {
      amount_unrounded: "US$980",
      currency: "USD",
      value: 980,
      amount_rounded: "US$980",
    },
    gross_amount: {
      amount_unrounded: "US$980",
      currency: "USD",
      value: 980,
      amount_rounded: "US$980",
    },
    has_long_stays_monthly_rate_price: 0,
    gross_amount_per_night: {
      amount_unrounded: "US$19.60",
      currency: "USD",
      value: 19.6,
      amount_rounded: "US$20",
    },
    excluded_amount: {
      amount_rounded: "US$199",
      currency: "USD",
      value: 199,
      amount_unrounded: "US$199",
    },
    all_inclusive_amount: {
      currency: "USD",
      value: 1179,
      amount_rounded: "US$1,179",
      amount_unrounded: "US$1,179",
    },
    benefits: [
      {
        icon: null,
        badge_variant: "constructive",
        name: "20% off",
        details:
          "You’re getting a reduced rate because this property is offering a discount.",
        identifier: "combined-discount",
        kind: "badge",
      },
      {
        icon: null,
        badge_variant: "constructive",
        details:
          "You’re getting a reduced rate because this property is offering a discount when you book from a mobile device.",
        identifier: "mobile-rate",
        name: "Mobile-only price",
        kind: "badge",
      },
    ],
    has_long_stays_weekly_rate_price: 0,
    items: [
      {
        inclusion_type: "excluded",
        item_amount: {
          amount_unrounded: "US$137.20",
          currency: "USD",
          value: 137.2,
          amount_rounded: "US$137",
        },
        kind: "charge",
        details: "14 % TAX",
        name: "TAX",
        base: {
          percentage: 14,
          kind: "percentage",
        },
      },
      {
        base: {
          kind: "percentage",
          percentage: 1,
        },
        name: "City tax",
        details: "1 % City tax",
        kind: "charge",
        item_amount: {
          amount_unrounded: "US$9.80",
          amount_rounded: "US$10",
          currency: "USD",
          value: 9.8,
        },
        inclusion_type: "excluded",
      },
      {
        base: {
          base_amount: 1,
          kind: "per_night",
        },
        name: "Cleaning fee",
        details: "You don't pay the cleaning fee thanks to Genius",
        kind: "charge",
        item_amount: {
          amount_unrounded: "US$50",
          value: 50,
          currency: "USD",
          amount_rounded: "US$50",
        },
        inclusion_type: "excluded",
      },
      {
        name: "Service charge",
        details: null,
        base: {
          kind: "per_stay",
          base_amount: 2,
        },
        item_amount: {
          amount_unrounded: "US$2",
          amount_rounded: "US$2",
          value: 2,
          currency: "USD",
        },
        inclusion_type: "excluded",
        kind: "charge",
      },
      {
        kind: "discount",
        item_amount: {
          amount_rounded: "US$245",
          currency: "USD",
          value: 245,
          amount_unrounded: "US$245",
        },
        base: {
          kind: "rate",
        },
        name: "Mobile-only price",
        identifier: "mobile-discount",
        details:
          "You're getting a reduced rate because you're using a mobile device.",
      },
    ],
    nr_stays: 1,
    strikethrough_amount: {
      value: 1225,
      currency: "USD",
      amount_rounded: "US$1,225",
      amount_unrounded: "US$1,225",
    },
  },
  composite_price_breakdown: {
    gross_amount: {
      amount_unrounded: "US$980",
      amount_rounded: "US$980",
      currency: "USD",
      value: 980,
    },
    net_amount: {
      value: 980,
      currency: "USD",
      amount_rounded: "US$980",
      amount_unrounded: "US$980",
    },
    gross_amount_per_night: {
      amount_rounded: "US$20",
      value: 19.6,
      currency: "USD",
      amount_unrounded: "US$19.60",
    },
    has_long_stays_monthly_rate_price: 0,
    excluded_amount: {
      amount_rounded: "US$199",
      currency: "USD",
      value: 199,
      amount_unrounded: "US$199",
    },
    benefits: [
      {
        kind: "badge",
        details:
          "You’re getting a reduced rate because this property is offering a discount.",
        identifier: "combined-discount",
        name: "20% off",
        badge_variant: "constructive",
        icon: null,
      },
      {
        icon: null,
        badge_variant: "constructive",
        kind: "badge",
        name: "Mobile-only price",
        details:
          "You’re getting a reduced rate because this property is offering a discount when you book from a mobile device.",
        identifier: "mobile-rate",
      },
    ],
    all_inclusive_amount: {
      value: 1179,
      currency: "USD",
      amount_rounded: "US$1,179",
      amount_unrounded: "US$1,179",
    },
    items: [
      {
        base: {
          percentage: 14,
          kind: "percentage",
        },
        details: "14 % TAX",
        name: "TAX",
        kind: "charge",
        inclusion_type: "excluded",
        item_amount: {
          amount_unrounded: "US$137.20",
          value: 137.2,
          currency: "USD",
          amount_rounded: "US$137",
        },
      },
      {
        inclusion_type: "excluded",
        item_amount: {
          amount_unrounded: "US$9.80",
          currency: "USD",
          value: 9.8,
          amount_rounded: "US$10",
        },
        kind: "charge",
        details: "1 % City tax",
        name: "City tax",
        base: {
          percentage: 1,
          kind: "percentage",
        },
      },
      {
        base: {
          base_amount: 2,
          kind: "per_stay",
        },
        details: null,
        name: "Service charge",
        kind: "charge",
        inclusion_type: "excluded",
        item_amount: {
          amount_rounded: "US$2",
          value: 2,
          currency: "USD",
          amount_unrounded: "US$2",
        },
      },
      {
        kind: "charge",
        inclusion_type: "excluded",
        item_amount: {
          value: 50,
          currency: "USD",
          amount_rounded: "US$50",
          amount_unrounded: "US$50",
        },
        base: {
          base_amount: 1,
          kind: "per_night",
        },
        details: "You don't pay the cleaning fee thanks to Genius",
        name: "Cleaning fee",
      },
      {
        base: {
          kind: "rate",
        },
        identifier: "mobile-discount",
        details:
          "You're getting a reduced rate because you're using a mobile device.",
        name: "Mobile-only price",
        kind: "discount",
        item_amount: {
          amount_unrounded: "US$245",
          amount_rounded: "US$245",
          value: 245,
          currency: "USD",
        },
      },
    ],
    has_long_stays_weekly_rate_price: 0,
    strikethrough_amount: {
      value: 1225,
      currency: "USD",
      amount_rounded: "US$1,225",
      amount_unrounded: "US$1,225",
    },
    discounted_amount: {
      amount_rounded: "US$245",
      currency: "USD",
      value: 245,
      amount_unrounded: "US$245",
    },
    strikethrough_amount_per_night: {
      amount_unrounded: "US$24.50",
      value: 24.5,
      currency: "USD",
      amount_rounded: "US$25",
    },
    gross_amount_hotel_currency: {
      amount_unrounded: "US$980",
      amount_rounded: "US$980",
      value: 980,
      currency: "USD",
    },
    included_taxes_and_charges_amount: {
      amount_rounded: "US$0",
      value: 0,
      currency: "USD",
      amount_unrounded: "US$0",
    },
    charges_details: {
      translated_copy: "+US$199 taxes and fees",
      amount: {
        value: 199,
        currency: "USD",
      },
      mode: "extra_charges",
    },
  },
  property_highlight_strip: [],
  sustainability: {
    sustainability_page: {
      level_details:
        "This property has told us they’re making large investments and efforts toward sustainability by taking steps that can have environmental and social impacts. We’ve worked with experts including Travalyst and Sustainalize to create the Travel Sustainable program – making it easier for you to experience the world more sustainably.",
      description:
        "These are the steps this property has taken to provide more sustainable and eco-friendly travel:",
      level: "L3",
      tier: "gold",
      efforts: [
        {
          title: "Waste",
          icon: "recycling_sign",
          steps: [
            "Single-use shampoo, conditioner, and body wash bottles not used",
            "Single-use plastic straws not used",
            "Single-use plastic cups not used",
            "Single-use plastic water bottles not used",
            "Single-use plastic bottles not used",
            "Single-use plastic cutlery/plates not used",
            "Water cooler/dispenser",
            "Single-use plastic stirrers not used",
            "Recycling bins available to guests and waste is recycled",
          ],
        },
        {
          title: "Water",
          steps: [
            "Option to reuse towels",
            "Option to opt out of daily room cleaning",
            "Water-efficient toilets",
            "Water-efficient showers",
          ],
          icon: "blood_drop",
        },
        {
          title: "Energy and greenhouse gases",
          steps: [
            "Most food provided at the property is locally sourced",
            "Most lighting throughout property uses energy-efficient LED bulbs",
            "The property makes efforts to reduce food waste",
            "Vegetarian menu options available",
            "Vegan menu options available ",
            "100% renewable electricity used throughout",
          ],
          icon: "renewable_energy_charging",
        },
        {
          icon: "group",
          steps: [
            "Invests a percentage of revenue back into community projects or sustainability projects",
            "Tours and activities organized by local guides and businesses",
            "Local artists are offered a platform to display their talents",
            "Provide guests with info about local ecosystems, history, culture, and visitor etiquette",
          ],
          title: "Destination and community",
        },
        {
          title: "Nature",
          steps: [
            "Green spaces like (rooftop) gardens at the property",
            "Most food provided is organic",
          ],
          icon: "tree",
        },
      ],
      sustainable_facility_count: 25,
      has_programmes: 0,
      cta: "Read more about Travel Sustainable",
      title: "Sustainability steps",
    },
    hotel_page: {
      has_badge: 1,
      cta: "Read more",
      title: "Travel Sustainable Level 3",
      description:
        "This property is part of the Travel Sustainable program, which means it’s taken significant steps to make your stay more sustainable.",
    },
    sustainability_level: {
      name: "L3",
      id: 3,
      title: "Travel Sustainable Level 3",
    },
  },
  facilities_block: {
    type: "popular",
    facilities: [
      {
        name: "Airport shuttle",
        icon: "shuttle",
      },
      {
        name: "Non-smoking rooms",
        icon: "nosmoking",
      },
      {
        icon: "clean",
        name: "Room service",
      },
      {
        name: "Private Parking",
        icon: "parking_sign",
      },
      {
        name: "Family rooms",
        icon: "family",
      },
      {
        icon: "parking_sign",
        name: "Free parking",
      },
      {
        name: "Free WiFi",
        icon: "wifi",
      },
    ],
    name: "Most Popular Facilities",
  },
  top_ufi_benefits: [
    {
      icon: "wifi",
      translated_name: "WiFi",
    },
    {
      translated_name: "Airport shuttle",
      icon: "shuttle",
    },
    {
      translated_name: "Family rooms",
      icon: "family",
    },
    {
      icon: "parking_sign",
      translated_name: "Parking",
    },
    {
      translated_name: "Non-smoking rooms",
      icon: "nosmoking",
    },
    {
      icon: "clean",
      translated_name: "Room service",
    },
  ],
  languages_spoken: {
    languagecode: ["ru", "it", "en-gb", "ar"],
  },
  spoken_languages: ["ru", "it", "en-gb", "ar"],
  breakfast_review_score: {
    rating: 0,
    review_snippet: "",
    review_number: 0,
    review_score: 0,
    review_score_word: "",
    review_count: 0,
  },
  wifi_review_score: {
    rating: 7.5,
  },
  info_banners: [
    {
      collapsible: 1,
      is_default_collapsed: 1,
      show_after_dismissed: 1,
      id: "coronavirus",
      show_after_dismissed_time: 24,
      dismissable: 0,
      position_to_inject: 0,
      title: "Coronavirus (COVID-19) support",
      type: "banner",
      primary_action: {
        text: "Read more",
        action_context: "covid19-faq",
        action: "open-page",
      },
      priority: 100,
      messages: [
        "Get the travel advice you need. Read more about possible travel restrictions before you go.",
      ],
      secondary_action: {},
    },
  ],
  min_room_distribution: {
    children: [],
    adults: 1,
  },
  available_deal_descriptions: [],
  tax_exceptions: [
    {
      tax_exception:
        "Under Egyptian law all foreign guests must pay in a foreign currency, not in Egyptian currency.",
      copy_tag:
        "Under Egyptian law all foreign guests must pay in a foreign currency, not in Egyptian currency.",
      ignore_on_sr_hp: 1,
    },
    {
      ignore_on_sr_hp: 0,
      tax_exception:
        "Egyptian citizens are required to pay in the local currency according to the exchange rate at the time of payment.",
      copy_tag:
        "Egyptian citizens are required to pay in the local currency according to the exchange rate at the time of payment.",
    },
  ],
  booking_home: {
    is_vacation_rental: 1,
    group: "hotels_and_others",
    house_rules: [
      {
        description: "No smoking",
        icon: "smoking",
        type: "POLICY_SMOKING",
        title: "Smoking",
      },
      {
        type: "POLICY_HOTEL_PETS",
        title: "Pets",
        icon: "petfriendly",
        description: "Pets are not allowed",
      },
      {
        title: "Parties",
        type: "POLICY_PARTIES",
        icon: "fooddrink",
        description: "Parties/events are not allowed.",
      },
    ],
    segment: 0,
    checkin_methods: [],
    is_single_type_property: 0,
    is_aparthotel: 0,
    quality_class: null,
    is_single_unit_property: 0,
    is_booking_home: 1,
  },
  aggregated_data: {
    has_kitchen: 0,
    common_kitchen_fac: [
      {
        name: "Electric kettle",
        id: 86,
      },
      {
        name: "Cleaning products",
        id: 116,
      },
    ],
    has_refundable: 1,
    has_nonrefundable: 1,
    has_seating: 1,
  },
  last_reservation: {
    country: null,
    time: "",
    countrycode: null,
  },
  free_facilities_cancel_breakfast: [
    {
      facility_id: 46,
    },
  ],
  room_recommendation: [
    {
      total_extra_bed_price_in_hotel_currency: 0,
      children: 0,
      extra_babycots_price_in_hotel_currency: 0,
      number_of_extra_beds_for_adults: 0,
      extra_beds_for_children_price: 0,
      extra_beds_for_adults_price: 0,
      number_of_extra_beds_for_children: 0,
      block_id: "898508904_373756334_0_0_0",
      adults: 1,
      total_extra_bed_price: 0,
      extra_beds_for_adults_price_in_hotel_currency: 0,
      number_of_extra_beds_and_babycots_total: 0,
      extra_babycots_price: 0,
      number_of_extra_babycots: 0,
      babies: 0,
      extra_beds_for_children_price_in_hotel_currency: 0,
    },
  ],
  hotel_text: {},
  districts: "",
  preferences: [],
  hotel_important_information_with_codes: [
    {
      executing_phase: 0,
      sentence_id: 28,
      phrase:
        "This property does not accommodate bachelor(ette) or similar parties.",
    },
  ],
  rooms: {
    898508904: {
      private_bathroom_highlight: {
        has_highlight: 0,
      },
      bed_configurations: [
        {
          bed_types: [
            {
              description_imperial: "35–51 inches wide",
              name: "Twin bed(s)",
              bed_type: 1,
              count: 2,
              name_with_count: "2 twin beds",
              description: "90–130 cm wide",
              description_localized: null,
            },
          ],
        },
      ],
      description:
        "This air-conditioned twin/double room features a shared bathroom, a washing machine, a private entrance as well as a balcony. The unit offers 2 beds.",
      facilities: [
        {
          name: "Shared bathroom",
          alt_facilitytype_id: 5,
          alt_facilitytype_name: "Bathroom",
          facilitytype_name: "Bathroom",
          facilitytype_id: 5,
          id: 24,
        },
        {
          facilitytype_id: 5,
          facilitytype_name: "Bathroom",
          id: 42,
          alt_facilitytype_name: "Bathroom",
          alt_facilitytype_id: 5,
          name: "Shared toilet",
        },
        {
          facilitytype_name: "Room Amenities",
          facilitytype_id: 4,
          id: 15,
          alt_facilitytype_name: "General",
          alt_facilitytype_id: 1,
          name: "Iron",
        },
        {
          alt_facilitytype_id: 1,
          name: "Fan",
          facilitytype_id: 4,
          facilitytype_name: "Room Amenities",
          id: 30,
          alt_facilitytype_name: "General",
        },
        {
          alt_facilitytype_id: 4,
          name: "Drying rack for clothing",
          facilitytype_name: "Room Amenities",
          facilitytype_id: 4,
          id: 140,
          alt_facilitytype_name: "Room Amenities",
        },
        {
          facilitytype_name: "Services & Extras",
          id: 124,
          facilitytype_id: 8,
          alt_facilitytype_name: "Bathroom",
          alt_facilitytype_id: 5,
          name: "Towels",
        },
        {
          id: 25,
          facilitytype_name: "Room Amenities",
          facilitytype_id: 4,
          alt_facilitytype_name: "General",
          alt_facilitytype_id: 1,
          name: "Ironing facilities",
        },
        {
          alt_facilitytype_id: 15,
          name: "Sitting area",
          facilitytype_name: "Room Amenities",
          id: 26,
          facilitytype_id: 4,
          alt_facilitytype_name: "Living Area",
        },
        {
          alt_facilitytype_id: 5,
          name: "Guest bathroom",
          facilitytype_name: "Bathroom",
          id: 72,
          facilitytype_id: 5,
          alt_facilitytype_name: "Bathroom",
        },
        {
          alt_facilitytype_id: 4,
          name: "Socket near the bed",
          facilitytype_name: "Room Amenities",
          id: 184,
          facilitytype_id: 4,
          alt_facilitytype_name: "Room Amenities",
        },
        {
          alt_facilitytype_id: 5,
          name: "Slippers",
          facilitytype_name: "Bathroom",
          facilitytype_id: 5,
          id: 43,
          alt_facilitytype_name: "Bathroom",
        },
        {
          alt_facilitytype_name: "Outdoors",
          id: 17,
          facilitytype_name: "Outdoor & View",
          facilitytype_id: 9,
          name: "Balcony",
          alt_facilitytype_id: 13,
        },
        {
          facilitytype_name: "Bathroom",
          id: 12,
          facilitytype_id: 5,
          alt_facilitytype_name: "Bathroom",
          alt_facilitytype_id: 5,
          name: "Hairdryer",
        },
        {
          alt_facilitytype_id: 14,
          name: "View",
          id: 81,
          facilitytype_name: "Outdoor & View",
          facilitytype_id: 9,
          alt_facilitytype_name: "View",
        },
        {
          facilitytype_id: 4,
          facilitytype_name: "Room Amenities",
          id: 80,
          alt_facilitytype_name: "General",
          alt_facilitytype_id: 1,
          name: "Tile/Marble floor",
        },
        {
          name: "Toilet",
          alt_facilitytype_id: 5,
          alt_facilitytype_name: "Bathroom",
          facilitytype_name: "Bathroom",
          id: 31,
          facilitytype_id: 5,
        },
        {
          alt_facilitytype_name: "General",
          facilitytype_name: "Room Amenities",
          facilitytype_id: 4,
          id: 76,
          name: "Private entrance",
          alt_facilitytype_id: 1,
        },
        {
          alt_facilitytype_name: "Kitchen",
          facilitytype_id: 7,
          facilitytype_name: "Food & Drink",
          id: 86,
          name: "Electric kettle",
          alt_facilitytype_id: 12,
        },
        {
          facilitytype_name: "Room Amenities",
          id: 40,
          facilitytype_id: 4,
          alt_facilitytype_name: "General",
          alt_facilitytype_id: 1,
          name: "Heating",
        },
        {
          alt_facilitytype_name: "Bathroom",
          facilitytype_id: 5,
          facilitytype_name: "Bathroom",
          id: 4,
          name: "Shower",
          alt_facilitytype_id: 5,
        },
        {
          alt_facilitytype_id: 12,
          name: "Washing machine",
          facilitytype_id: 4,
          facilitytype_name: "Room Amenities",
          id: 34,
          alt_facilitytype_name: "Kitchen",
        },
        {
          alt_facilitytype_id: 17,
          name: "Wardrobe or closet",
          facilitytype_name: "Room Amenities",
          id: 95,
          facilitytype_id: 4,
          alt_facilitytype_name: "Bedroom",
        },
        {
          alt_facilitytype_name: "Kitchen",
          facilitytype_name: "Room Amenities",
          facilitytype_id: 4,
          id: 116,
          name: "Cleaning products",
          alt_facilitytype_id: 12,
        },
        {
          alt_facilitytype_name: "Bathroom",
          id: 141,
          facilitytype_name: "Bathroom",
          facilitytype_id: 5,
          name: "Toilet paper",
          alt_facilitytype_id: 5,
        },
        {
          name: "Mosquito net",
          alt_facilitytype_id: 1,
          alt_facilitytype_name: "General",
          facilitytype_id: 4,
          facilitytype_name: "Room Amenities",
          id: 90,
        },
        {
          facilitytype_name: "Room Amenities",
          id: 11,
          facilitytype_id: 4,
          alt_facilitytype_name: "General",
          alt_facilitytype_id: 1,
          name: "Air conditioning",
        },
        {
          alt_facilitytype_id: 15,
          name: "Dining area",
          facilitytype_name: "Food & Drink",
          facilitytype_id: 7,
          id: 85,
          alt_facilitytype_name: "Living Area",
        },
        {
          alt_facilitytype_id: 40,
          name: "Hand sanitizer",
          facilitytype_name: "Cleanliness & disinfection",
          facilitytype_id: 40,
          id: 231,
          alt_facilitytype_name: "Cleanliness & disinfection",
        },
      ],
      is_high_floor_guaranteed: 0,
      highlights: [
        {
          icon: "wifi",
          translated_name: "Free WiFi",
        },
        {
          icon: "checkmark",
          id: 17,
          translated_name: "Balcony",
        },
        {
          icon: "mountains",
          translated_name: "View",
          id: 81,
        },
        {
          icon: "snowflake",
          id: 11,
          translated_name: "Air conditioning",
        },
      ],
      children_and_beds_text: {
        cribs_and_extra_beds: [
          {
            text: "No capacity for extra beds or cribs.",
            highlight: 0,
          },
        ],
        allow_children: 1,
        children_at_the_property: [
          {
            text: "Children of all ages are welcome.",
            highlight: 0,
          },
          {
            text: "Children 18 and above are considered adults at this property.",
            highlight: 0,
          },
          {
            highlight: 1,
            text: "To see correct prices and occupancy info, add the number and ages of children in your group to your search.",
          },
        ],
        age_intervals: [],
      },
      photos: [],
      private_bathroom_count: 0,
    },
  },
  block: [
    {
      is_flash_deal: 0,
      paymentterms: {
        cancellation: {
          type_translation: "Non-refundable",
          non_refundable_anymore: 0,
          guaranteed_non_refundable: 0,
          type: "non_refundable",
          bucket: "SMP_NON_REF",
          description:
            "If you cancel, modify the booking, or don't show up, the fee will be the total price of the reservation.",
          info: {
            timezone_offset: null,
            date_before_raw: null,
            date: null,
            refundable_date: null,
            date_raw: null,
            time: null,
            time_before_midnight: null,
            refundable: 0,
            date_before: null,
            timezone: null,
            is_midnight: null,
          },
        },
        prepayment: {
          extended_type_translation: "SECURE YOUR BOOKING – pay now",
          type_translation: "SECURE YOUR BOOKING – pay now",
          type: "full_prepayment",
          type_extended: "non_refundable_prepayment",
          description:
            "You'll be charged a prepayment of the total price at any time.",
          simple_translation: "Prepayment",
          info: {
            prepayment_at_booktime: 1,
          },
        },
      },
      mealplan: "There is no meal option with this room.",
      is_last_minute_deal: 0,
      all_inclusive: 0,
      number_of_bathrooms: 1,
      half_board: 0,
      pod_ios_migrate_policies_to_smp_fullon: 0,
      smoking: 0,
      babycots_available_amount: null,
      refundable_until: "",
      nr_children: 0,
      deposit_required: 1,
      full_board: 0,
      genius_discount_percentage: 0,
      block_text: {
        policies: [
          {
            class: "POLICY_CANCELLATION",
            content:
              "If you cancel, modify the booking, or don't show up, the fee will be the total price of the reservation.",
          },
          {
            class: "POLICY_PREPAY",
            content:
              "The total price of the reservation is charged at the time of booking.",
          },
          {
            content:
              "Booking.com takes your payment for this stay, but make sure you have cash for any extras once you get there.",
            class: "POLICY_BMP",
            title: "Payments by Booking.com",
          },
          {
            content: "General",
            class: "POLICY_TITLE",
          },
          {
            class: "POLICY_REFUND_SCHEDULE",
            content:
              " You won't be eligible for a refund if you cancel this booking.",
          },
        ],
      },
      room_id: 898508904,
      name: "Double or Twin Room - Non-refundable",
      is_secret_deal: 0,
      room_surface_in_feet2: 269.09776,
      block_id: "898508904_373756334_0_0_0",
      deals: {
        deal_attributes: {
          has_secret_channel_option: 0,
        },
      },
      bh_room_highlights: [],
      roomtype_id: 24,
      room_count: 1,
      is_smart_deal: 0,
      can_reserve_free_parking: 1,
      name_without_policy: "Double or Twin Room",
      babycots_available: 0,
      number_of_bedrooms: 0,
      breakfast_included: 0,
      must_reserve_free_parking: 0,
      room_name: "Double or Twin Room",
      extrabed_available: 0,
      nr_adults: 2,
      children_ages: [],
      room_surface_in_m2: 25,
      refundable: 0,
      is_vp2_enrolled: 1,
      is_domestic_rate: 0,
      max_children_free: 0,
      pay_in_advance: 1,
      max_occupancy: "2",
      max_children_free_age: 12,
      is_block_fit: 1,
      extrabed_available_amount: null,
      is_genius_deal: null,
    },
  ],
};

export const dummyDescription = {
  description:
    "Ideally set in the Powai district of Mumbai, Treebo Trend Elvis Inn, Chandivali is located 2.3 miles from Powai Lake, 2.7 miles from Indian Institute of Technology, Bombay and 2.8 miles from Phoenix Market City Mall. This 3-star hotel offers room service, a 24-hour front desk and free WiFi. The hotel has family rooms. At the hotel, the rooms include a desk, a flat-screen TV, a private bathroom, bed linen and towels. All rooms at Treebo Trend Elvis Inn, Chandivali have air conditioning and a closet. Guests at the accommodation can enjoy a continental or a vegetarian breakfast. Bombay Exhibition Centre is 5 miles from Treebo Trend Elvis Inn, Chandivali, while ISKCON is 5.3 miles from the property. The nearest airport is Chhatrapati Shivaji International Mumbai Airport, 1.9 miles from the hotel.",
};
